In [23]:
!pip install pandas==0.24.2

  Found existing installation: pandas 1.3.5
    Uninstalling pandas-1.3.5:
      Successfully uninstalled pandas-1.3.5


In [1]:
filename='virus dataset.fasta'

In [2]:
from Bio import SeqIO
import keras
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer


C:\Users\Administrator\anaconda3\envs\pytorchenv\lib\site-packages\sklearn\utils\validation.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  LARGE_SPARSE_SUPPORTED = LooseVersion(scipy_version) >= '0.14.0'
C:\Users\Administrator\anaconda3\envs\pytorchenv\lib\site-packages\sklearn\feature_extraction\image.py:167: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.int):


In [3]:
seq_obj=SeqIO.parse(filename,'fasta')

In [4]:
sequences=[]

In [5]:
for seq in seq_obj:
    sequences.append(seq)

In [6]:
len(sequences)

34550

In [7]:
for record in sequences:
    seq_id=record.id
    seq_name=record.name
    seq_desc=record.description
    sequence=record.seq
    length=len(sequence)

In [8]:
seq_ids=[]
seq_lengths=[]
seqs=[]
seq_descs=[]
label=[]

In [9]:
for record in sequences:
    seq_id=record.id
    sequence=record.seq[200:1300]
    seq_desc=record.description
    if('coronavirus' in seq_desc):
        label.append('COVID-19')
    elif('Dengue' in seq_desc):
        label.append('Dengue')
    elif('Monkeypox' in seq_desc):
        label.append('Monkeypox')
    elif('Hepatitis B' in seq_desc):
        label.append('Hepatitis B')
    elif('Hepatitis C' in seq_desc):
        label.append('Hepatitis C')
    elif('HIV' in seq_desc):
        label.append('HIV')
    elif('Human respiratory syncytial' in seq_desc):
        label.append('Human orthopneumovirus')
    elif('TTV-like' in seq_desc):
        label.append('TTV-like')
    elif('Influenza A' in seq_desc):
        label.append('Influenza A')
    else:
        label.append(None)
    
    length=len(sequence)
    
    seq_ids.append(seq_id)
    seq_descs.append(seq_desc)
    
    seq_lengths.append(length)
    seqs.append(sequence)

In [10]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [11]:
dataframe=pd.DataFrame()
dataframe['seq_id']=seq_ids
dataframe['seq_desc']=seq_descs
dataframe['label']=label
dataframe['seq_length']=seq_lengths
dataframe['Dna Seq']=seqs

In [12]:
dataframe=dataframe[dataframe['seq_length'].notnull()]
dataframe=dataframe[dataframe['label'].notnull()]


In [13]:
dataframe.head(15)

seq_id                                           seq_desc      label  \
10  ON675438.1  ON675438.1 Monkeypox virus isolate MPXV_USA_20...  Monkeypox   
11  JX878429.1  JX878429.1 Monkeypox virus isolate DRC 07-0662...  Monkeypox   
12  JX878428.1  JX878428.1 Monkeypox virus isolate DRC 07-0514...  Monkeypox   
13  JX878427.1  JX878427.1 Monkeypox virus isolate DRC 07-0480...  Monkeypox   
14  JX878426.1  JX878426.1 Monkeypox virus isolate DRC 07-0450...  Monkeypox   
15  JX878425.1  JX878425.1 Monkeypox virus isolate DRC 07-0354...  Monkeypox   
16  JX878424.1  JX878424.1 Monkeypox virus isolate DRC 07-0338...  Monkeypox   
17  JX878423.1  JX878423.1 Monkeypox virus isolate DRC 07-0337...  Monkeypox   
18  JX878422.1  JX878422.1 Monkeypox virus isolate DRC 07-0287...  Monkeypox   
19  JX878421.1  JX878421.1 Monkeypox virus isolate DRC 07-0286...  Monkeypox   
20  JX878420.1  JX878420.1 Monkeypox virus isolate DRC 07-0283...  Monkeypox   
21  JX878419.1  JX878419.1 Monkeypox virus isolate DRC 07-0275...  Monkeypox   
22  JX878418.1  JX878418.1 Monkeypox virus isolate DRC 07-0120...  Monkeypox   
23  JX878417.1  JX878417.1 Monkeypox virus isolate DRC 07-0104...  Monkeypox   
24  JX878416.1  JX878416.1 Monkeypox virus isolate DRC 07-0093...  Monkeypox   

    seq_length                                            Dna Seq  
10        1100  (C, G, A, A, G, A, G, A, G, A, A, A, G, A, G, ...  
11        1100  (A, A, A, C, T, T, T, T, T, A, C, G, A, C, T, ...  
12        1100  (A, A, A, C, T, T, T, T, T, A, C, G, A, C, T, ...  
13        1100  (A, A, A, C, T, T, T, T, T, A, C, G, A, C, T, ...  
14        1100  (G, T, T, A, G, T, C, A, A, G, A, T, A, T, T, ...  
15        1100  (A, A, A, C, T, T, T, T, T, A, C, G, A, C, T, ...  
16        1100  (A, A, A, C, T, T, T, T, T, A, C, G, A, C, T, ...  
17        1100  (A, A, A, C, T, T, T, T, T, A, C, G, A, C, T, ...  
18        1100  (A, A, A, C, T, T, T, T, T, A, C, G, A, C, T, ...  
19        1100  (A, A, A, C, T, T, T, T, T, A, C, G, A, C, T, ...  
20        1100  (G, T, T, A, G, T, C, A, A, G, A, T, A, T, T, ...  
21        1100  (G, T, T, A, G, T, C, A, A, G, A, T, A, T, T, ...  
22        1100  (G, T, T, A, G, T, C, A, A, G, A, T, A, T, T, ...  
23        1100  (A, A, A, C, T, T, T, T, T, A, C, G, A, C, T, ...  
24        1100  (A, A, A, C, T, T, T, T, T, A, C, G, A, C, T, ...

In [14]:
dataframe['label'].value_counts()

Hepatitis B               8625
HIV                       5106
Dengue                    4333
TTV-like                  2487
Human orthopneumovirus    1724
Monkeypox                 1031
COVID-19                   875
Hepatitis C                811
Influenza A                545
Name: label, dtype: int64

In [15]:
dataframe=dataframe.drop(['seq_id','seq_length','seq_desc'],axis=1)

In [16]:
dataframe.tail(15)

label                                            Dna Seq
34434   HIV  (T, C, A, T, C, A, C, A, C, A, G, C, C, C, G, ...
34435   HIV  (T, C, A, T, C, A, C, G, T, G, G, C, C, C, G, ...
34436   HIV  (G, A, G, A, A, A, A, T, T, A, G, G, T, T, A, ...
34437   HIV  (G, A, G, A, A, A, A, T, T, A, G, G, T, T, A, ...
34438   HIV  (G, A, G, A, G, A, A, T, T, A, A, G, T, T, A, ...
34439   HIV  (G, A, G, A, A, A, A, T, T, A, G, G, T, T, A, ...
34440   HIV  (G, A, G, A, A, A, A, T, T, A, G, G, T, T, A, ...
34441   HIV  (G, A, G, A, A, A, A, T, T, A, G, G, T, T, A, ...
34442   HIV  (G, A, A, A, A, A, A, T, T, A, G, G, T, T, A, ...
34443   HIV  (G, A, G, A, A, A, A, T, T, A, G, G, T, T, A, ...
34444   HIV  (G, A, G, A, A, A, A, T, T, A, G, G, T, T, A, ...
34445   HIV  (G, A, G, A, A, A, A, T, T, A, G, G, T, T, A, ...
34446   HIV  (T, A, G, A, A, C, A, G, T, T, A, C, A, G, T, ...
34447   HIV  (T, C, T, C, A, A, G, A, C, A, G, G, A, T, C, ...
34475   HIV  (G, G, A, G, G, C, T, A, G, A, A, G, G, A, G, ...

In [17]:
def clean_Labels(x):
    
    if x=='Monkeypox':
        return 0
    if x == 'HIV':
        return 1
    if x=='Dengue':
        return 2
    if x == 'Human orthopneumovirus':
        return 3
    if x=='Hepatitis B':
        return 4
    if x == 'COVID-19':
        return 5
    if x=='Hepatitis C':
        return 6
    if x=='TTV-like':
        return 7
    if x=='Influenza A':
        return 8
    
    
    return float(x)

In [18]:
dataframe['label']=dataframe['label'].apply(clean_Labels)

In [19]:
dataframe['label'].to_numpy()

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [20]:
dataframe['label'].unique()

array([0, 1, 4, 2, 5, 3, 6, 7, 8], dtype=int64)

In [21]:
dataframe.head()

label                                            Dna Seq
10      0  (C, G, A, A, G, A, G, A, G, A, A, A, G, A, G, ...
11      0  (A, A, A, C, T, T, T, T, T, A, C, G, A, C, T, ...
12      0  (A, A, A, C, T, T, T, T, T, A, C, G, A, C, T, ...
13      0  (A, A, A, C, T, T, T, T, T, A, C, G, A, C, T, ...
14      0  (G, T, T, A, G, T, C, A, A, G, A, T, A, T, T, ...

In [22]:
dataframe['Dna Seq']=dataframe['Dna Seq'].astype(str)

In [23]:
dataframe.head()

label                                            Dna Seq
10      0  CGAAGAGAGAAAGAGATGGTTAGTCAAGATATTTTTCTTAGTACAA...
11      0  AAACTTTTTACGACTCCATCAGAAAGAGGTTTAATATTTTTGTGAG...
12      0  AAACTTTTTACGACTCCATCAGAAAGAGGTTTAATATTTTTGTGAG...
13      0  AAACTTTTTACGACTCCATCAGAAAGAGGTTTAATATTTTTGTGAG...
14      0  GTTAGTCAAGATATTTTTCTTAGTACAAAAGTCAATGTTTTAAAAT...

In [24]:
def Kmers_funct(seq, size=4):
    return [seq[x:x+size].lower() for x in range(len(seq) - size + 1)]

In [25]:
dataframe['words'] = dataframe.apply(lambda x: Kmers_funct(x['Dna Seq']), axis=1)
dataframe = dataframe.drop('Dna Seq', axis=1)

In [26]:
dataframe.head()

label                                              words
10      0  [cgaa, gaag, aaga, agag, gaga, agag, gaga, aga...
11      0  [aaac, aact, actt, cttt, tttt, tttt, ttta, tta...
12      0  [aaac, aact, actt, cttt, tttt, tttt, ttta, tta...
13      0  [aaac, aact, actt, cttt, tttt, tttt, ttta, tta...
14      0  [gtta, ttag, tagt, agtc, gtca, tcaa, caag, aag...

In [27]:
dna_texts = list(dataframe['words'])
for item in range(len(dna_texts)):
    dna_texts[item] =' '.join(dna_texts[item])

In [28]:
y_data = dataframe.iloc[:, 0].values

In [29]:
y_data

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [30]:
# Pre-processing of DNA sequences using CountVectorizer
vectorizer = CountVectorizer(analyzer='char', ngram_range=(4,4))
X = vectorizer.fit_transform(dna_texts)

In [31]:
X.shape

(25537, 6627)

In [32]:
y_data.shape

(25537,)

In [33]:
y = keras.utils.to_categorical(y_data, num_classes=9)

In [34]:
y.shape

(25537, 9)

In [35]:
def create_model(input_shape, num_classes, type='CNN'):
    model = keras.Sequential()
    model.add(keras.layers.Reshape((input_shape[0], 1), input_shape=input_shape))
    model.add(keras.layers.Conv1D(filters=32, kernel_size=3, activation='relu'))
    model.add(keras.layers.MaxPooling1D(pool_size=2))
    model.add(keras.layers.Flatten())
    model.add(keras.layers.Dense(32, activation='relu'))
    model.add(keras.layers.Dense(num_classes, activation='softmax'))
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    return model

In [36]:
# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [37]:
# Convert sparse matrix to dense matrix
X_train = X_train.toarray()
X_test = X_test.toarray()

# Reshape the input to add the sequence length dimension
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))

In [39]:
model = create_model(X_train.shape[1:], 9)

In [40]:
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/10
639/639 [==============================] - 50s 77ms/step - loss: 0.1845 - accuracy: 0.9771 - val_loss: 0.0522 - val_accuracy: 0.9994
Epoch 2/10
639/639 [==============================] - 49s 77ms/step - loss: 0.0175 - accuracy: 0.9984 - val_loss: 0.0162 - val_accuracy: 0.9988
Epoch 3/10
639/639 [==============================] - 50s 77ms/step - loss: 0.0067 - accuracy: 0.9993 - val_loss: 0.0047 - val_accuracy: 0.9994
Epoch 4/10
639/639 [==============================] - 51s 79ms/step - loss: 5.0067e-04 - accuracy: 0.9998 - val_loss: 0.0104 - val_accuracy: 0.9994
Epoch 5/10
639/639 [==============================] - 50s 79ms/step - loss: 0.0019 - accuracy: 0.9997 - val_loss: 0.0097 - val_accuracy: 0.9992
Epoch 6/10
639/639 [==============================] - 50s 78ms/step - loss: 0.0135 - accuracy: 0.9973 - val_loss: 0.0015 - val_accuracy: 0.9996
Epoch 7/10
639/639 [==============================] - 49s 77ms/step - loss: 0.0069 - accuracy: 0.9988 - val_loss: 0.0091 - val_accur

In [41]:
# Evaluate the model on test data
test_loss, test_acc = model.evaluate(X_test, y_test)
print("Test Loss:", test_loss)
print("Test Accuracy:", test_acc)

160/160 [==============================] - 3s 19ms/step - loss: 0.0023 - accuracy: 0.9996
Test Loss: 0.0022881932090967894
Test Accuracy: 0.9996084570884705


In [42]:
# Save the model
keras.models.save_model(model, 'model.h5')